version: "1.0"
services:
  mongodb: 
    image: mongo:latest
    container_name: mongodb_3
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_3:/data/db
    
  backend:
    build: .
    container_name: backend_3
    depends_on:
      - mongodb
    ports: 
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb_3:27017/test_3

volumes:
  mongodb_data_3: